export default {
  patient_name_surname: {id: 'patient_name_surname', required: true},
  patient_birthdate: {id: 'patient_birthdate', required: false},
  has_medical_treatment: {id: 'has_medical_treatment', required: true},
  has_medical_treatment_desc: {
    id: 'has_medical_treatment_desc',
    required: false,
  },
  has_medical_operation: {id: 'has_medical_operation', required: true},
  has_medical_operation_desc: {
    id: 'has_medical_operation_desc',
    required: false,
  },
  has_frequent_medicine: {id: 'has_frequent_medicine', required: true},
  has_frequent_medicine_desc: {
    id: 'has_frequent_medicine_desc',
    required: false,
  },
  Blood_Thinner: {id: 'Blood_Thinner', required: false},
  Blood_Pressure_Medicine: {id: 'Blood_Pressure_Medicine', required: false},
  Heart_Medicine: {id: 'Heart_Medicine', required: false},
  Cortisone: {id: 'Cortisone', required: false},
  Cholesterol_Medicine: {id: 'Cholesterol_Medicine', required: false}, 
  Diabetes_Medicine: {id: 'Diabetes_Medicine', required: false},
  Asthma_Medicine: {id: 'Asthma_Medicine', required: false},
  Thyroid_Medicine: {id: 'Thyroid_Medicine', required: false},
  Osteoporosis_Medicine: {id: 'Osteoporosis_Medicine', required: false},
  use_bisphosphonates_medicine: {
    id: 'use_bisphosphonates_medicine',
    required: true,
  },
  use_bisphosphonates_medicine_desc: {
    id: 'use_bisphosphonates_medicine_desc',
    required: false,
  },
  has_allergy_to_medicine: {id: 'has_allergy_to_medicine', required: true},
  Penicillin: {id: 'Penicillin', required: false},
  Painkiller: {id: 'Painkiller', required: false},
  Local_Anesthesia_Substance: {
    id: 'Local_Anesthesia_Substance',
    required: false,
  },
  Other_allergic_medicine: {id: 'Other_allergic_medicine', required: false},
  Other_allergic_medicine_desc: {
    id: 'Other_allergic_medicine_desc',
    required: false,
  },
  smoking: {id: 'smoking', required: false},
  smoking_count: {id: 'smoking_count', required: false},
  Heart_Attack: {id: 'Heart_Attack', required: false},
  Palpitations: {id: 'Palpitations', required: false},
  Congenital_Heart_Disease: {id: 'Congenital_Heart_Disease', required: false},
  Cardiac_Surgery: {id: 'Cardiac_Surgery', required: false},
  Chest_Pain: {id: 'Chest_Pain', required: false},
  Low_High_Blood_Pressure: {id: 'Low_High_Blood_Pressure', required: false},
  Rheumatic_Fever: {id: 'Rheumatic_Fever', required: false},
  Rheumatism: {id: 'Rheumatism', required: false},
  Osteoporosis: {id: 'Osteoporosis', required: false},
  Paralysis: {id: 'Paralysis', required: false},
  Thyroid: {id: 'Thyroid', required: false},
  Ulcer: {id: 'Ulcer', required: false},
  Asthma: {id: 'Asthma', required: false},
  COPD: {id: 'COPD', required: false},
  Sinusitis: {id: 'Sinusitis', required: false},
  Tuberculosis: {id: 'Tuberculosis', required: false},
  Epilepsy: {id: 'Epilepsy', required: false},
  Hepatitis: {id: 'Hepatitis', required: false},
  Kidney_Disease: {id: 'Kidney_Disease', required: false},
  Urticaria: {id: 'Urticaria', required: false},
  Blood_Disease: {id: 'Blood_Disease', required: false},
  Anemia: {id: 'Anemia', required: false},
  Long_Bleeding_Time: {id: 'Long_Bleeding_Time', required: false},
  Glaucoma: {id: 'Glaucoma', required: false},
  Diabetes: {id: 'Diabetes', required: false},
  HIV: {id: 'HIV', required: false},
  Cancer: {id: 'Cancer', required: false},
  Radiotherapy: {id: 'Radiotherapy', required: false},
  Chemotherapy: {id: 'Chemotherapy', required: false},
  Other_medical_status: {id: 'Other_medical_status', required: false},
  Other_medical_status_desc: {id: 'Other_medical_status_desc', required: false},
  pregnent: {id: 'pregnent', required: false},
  breastfeeding: {id: 'breastfeeding', required: false},
  patient_hand_declaration: {id: 'patient_hand_declaration', required: true},
  patient_signature: {id: 'patient_signature', required: true},
  patient_date: {id: 'patient_date', required: true},
  responsible_name_surname: {id: 'responsible_name_surname', required: true},
  responsible_signature: {id: 'responsible_signature', required: true},
  responsible_date: {id: 'responsible_date', required: true},
  doctor_name_surname: {id: 'doctor_name_surname', required: false},
  doctor_signature: {id: 'doctor_signature', required: false},
  doctor_date: {id: 'doctor_date', required: false},
  email_address: {id: 'email_address', required: true},
};
